---
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: prometheus
  namespace: default
  labels:
    prometheus: prometheus
spec:
  staticConfigs:
    - labels:
        job: prometheus
      targets:
        - localhost:9090