apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: alertmanager
  namespace: default
  labels:
    prometheus: prometheus
    app.kubernetes.io/name: alertmanager
spec:
  staticConfigs:
    - labels:
        job: alertmanager
      targets:
        - alertmanager-service:9093