---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- blackbox_serviceacc.yml
- blackbox_clusterrole.yml
- blackbox_config.yml
- blackbox_netpolicy.yml
- blackbox_rolebinding.yml
- blackbox_deployment.yml
- blackbox_service.yml
- blackbox_scrapeconfig.yml
